insert into MONEY (MONEY_COST, MONEY_NAME,MONEY_COUNT) values (14, '123', 1);
insert into MONEY (MONEY_COST, MONEY_NAME,MONEY_COUNT) values (14, '123', 1);
insert into MONEY (MONEY_COST, MONEY_NAME,MONEY_COUNT) values (14, '123', 1);